### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by guys1971** [diggy/wp-what-links-here#1]
Hi,

For some reason the plugin stopped working after the last update.  i.e pages created recently  that have the shortcode included no longer show referring inks 

I have tried uninstalling and reinstalling but this has not effect.  As the site using it is part of a network I have tried locally activating and network activating but to no avail.

The plugin still appears in the chron job list and pages that had the shortcode included before the plugin stopped working still show inbound links.

What I can do to debug this?  Could it be another plugin interferring?

Cheers,

Guy

**Comment by diggy** [comment]
@guys1971 thanks for the report. So, the plugin stopped working after you updated wp core from ... to 4.1? Could you share some more details about your specific setup? Plugins used and their versions? Did you implement any wp-what-links-here customizations (filters, constants)? I'll try to do some more testing asap.

**Comment by guys1971** [comment]
Thanks for your reply.  Your plugin is excellent.  :)

It did seem to stop working around the time of the 4.1 update.  I use wordpress to run the site evelynsdiary.com, specifically to power the "referring entries" elements.  For example:  http://evelynsdiary.com/encyclopedia/battles/edgehill/

The shortcode still works on older pages for example:
http://evelynsdiary.com/encyclopedia/people/nobility/thomas-howard-21st-earl-of-arundel/

I have 3 other sites as part of a network setup and the shortcode no longer works on any of these.

I just use the shortcode in page with no customisations or filters - just the basic shortcode.

I have the following plugins:
Akismet
Category Tag Pages Version 1.0  
Civil Footnotes 1.3.1
CMS Tree Page View 1.2.30
Comprehensive Google Map Plugin 9.1.2
Jetpack 3.3
Limit login attempts 1.7.1
List category posts 0.54.2
List pages shortcode 1.7.1
No self pings  0.2
​Tabby responsive tabs 1.2.1
WPBeginner's Compact Archives 3.0.3

**Comment by diggy** [comment]
@guys1971 I did some preliminary testing with wp 4.1 + 2014 default theme and encountered no problems with interlinking posts and pages. Will continue investigation tomorrow!

**Comment by guys1971** [comment]
Thanks for that. As an experiment, I will try deactivating all other
plugins.  :)

**Comment by diggy** [comment]
@guys1971 no trouble with the plugins you're using, the bug seems to be multisite related. I'll try to isolate the issue and release a fix asap.

**Comment by diggy** [comment]
@guys1971 the issue should be fixed with version [1.0.2](https://github.com/diggy/wp-what-links-here/releases/tag/1.0.2). Let me know if it's not the case!

NB: If you remember which posts and/or pages the plugin has failed to process due to the bug, you could manually build a queue with the relevant IDs, add it with e.g. `update_option( '_wp_wlh_cron_queue', '41,43,46' );` (or edit the `_wp_wlh_cron_queue` option directly in the database), and run the cron job with the wp-crontrol plugin.

**Comment by guys1971** [comment]
Hey thanks Peter!

Plugin now works again.  Thanks for the awesome support.

Guy
